### ISSUE TITLE
issue with hotel-app-rate

### ISSUE THREAD

**Issue by alansong21** [barabanshek/MIT_PRIMEs#15]
When running benchmarks, `hotel-app-rate` seems to have errors quite often.

Here is the output from `kubectl describe pod <hotel-app-rate pod>`:

```
Name:         hotel-app-rate-6ccdc95c48-xzwd2
Namespace:    default
Priority:     0
Node:         node-2.alan.ragger-pg0.utah.cloudlab.us/128.110.218.174
Start Time:   Sat, 26 Aug 2023 11:01:13 -0600
Labels:       app=hotel-app-rate
              pod-template-hash=6ccdc95c48
Annotations:  cni.projectcalico.org/podIP: 192.168.2.36/32
              cni.projectcalico.org/podIPs: 192.168.2.36/32
Status:       Running
IP:           192.168.2.36
IPs:
  IP:           192.168.2.36
Controlled By:  ReplicaSet/hotel-app-rate-6ccdc95c48
Containers:
  relay:
    Container ID:  containerd://747cf29b48028a3073c09d66c76e0bfb6386d073df9ae11563df2c3c45287cd8
    Image:         docker.io/vhiveease/relay:latest
    Image ID:      docker.io/vhiveease/relay@sha256:56e136940fb32ce0c884ee99d48aa0d2fe307f69b66d9170c9213bf338365f57
    Port:          50000/TCP
    Host Port:     0/TCP
    Args:
      --addr=0.0.0.0:50000
      --function-endpoint-url=0.0.0.0
      --function-endpoint-port=8083
      --function-name=rate
      --value=1
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 26 Aug 2023 11:01:31 -0600
      Finished:     Sat, 26 Aug 2023 11:01:32 -0600
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2k47p (ro)
  function:
    Container ID:  containerd://70e9ce4dec013d329a426d3fc5eeac12573d4db96caa9597456048b1e55484f4
    Image:         docker.io/vhiveease/hotel-app-rate:latest
    Image ID:      docker.io/vhiveease/hotel-app-rate@sha256:66cc1c70ffb5cbe71549a8e97d01bdbf9e07237035a0d9ca4dc847bb60ea602f
    Port:          50000/TCP
    Host Port:     0/TCP
    Args:
      --url=0.0.0.0
      --port=8083
      --db_addr=hotel-app-database:27017
      --memcached_addr=hotel-app-mmc:11211
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 26 Aug 2023 11:01:31 -0600
      Finished:     Sat, 26 Aug 2023 11:01:32 -0600
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2k47p (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-2k47p:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  35s                default-scheduler  Successfully assigned default/hotel-app-rate-6ccdc95c48-xzwd2 to node-2.alan.ragger-pg0.utah.cloudlab.us
  Normal   Pulled     34s                kubelet            Successfully pulled image "docker.io/vhiveease/hotel-app-rate:latest" in 458.812246ms
  Normal   Pulled     34s                kubelet            Successfully pulled image "docker.io/vhiveease/relay:latest" in 498.85519ms
  Normal   Pulled     32s                kubelet            Successfully pulled image "docker.io/vhiveease/relay:latest" in 441.370367ms
  Normal   Pulled     31s                kubelet            Successfully pulled image "docker.io/vhiveease/hotel-app-rate:latest" in 440.540834ms
  Normal   Started    31s (x2 over 34s)  kubelet            Started container function
  Normal   Created    31s (x2 over 34s)  kubelet            Created container function
  Warning  BackOff    28s (x2 over 29s)  kubelet            Back-off restarting failed container
  Warning  BackOff    28s (x2 over 29s)  kubelet            Back-off restarting failed container
  Normal   Pulling    18s (x3 over 35s)  kubelet            Pulling image "docker.io/vhiveease/relay:latest"
  Normal   Pulling    17s (x3 over 34s)  kubelet            Pulling image "docker.io/vhiveease/hotel-app-rate:latest"
  Normal   Started    17s (x3 over 34s)  kubelet            Started container relay
  Normal   Created    17s (x3 over 34s)  kubelet            Created container relay
  Normal   Pulled     17s                kubelet            Successfully pulled image "docker.io/vhiveease/relay:latest" in 442.368242ms
  ```
  
  And the YAML manifest:
  
  ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app-rate
  namespace: default
  labels:
    app: hotel-app-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app-rate
  template:
    metadata:
      labels:
        app: hotel-app-rate
    spec:
      containers:
        # Relay --------------
        - name: relay
          image: docker.io/vhiveease/relay:latest
          ports:
            - name: h2c
              containerPort: 50000
          args:
            - --addr=0.0.0.0:50000
            - --function-endpoint-url=0.0.0.0
            - --function-endpoint-port=8083
            - --function-name=rate
            - --value=1

        # Function ------------
        - name: function
          image: docker.io/vhiveease/hotel-app-rate:latest
          args:
            - --url=0.0.0.0
            - --port=8083
            - --db_addr=hotel-app-database:27017
            - --memcached_addr=hotel-app-mmc:11211
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-app-rate
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hotel-app-rate
  ports:
  - port: 50000
    targetPort: 50000
```
